# Generated by Django 3.1.7 on 2021-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
