# Generated by Django 3.1.7 on 2021-03-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatatuCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okota', models.CharField(max_length=10)),
                ('mwaga', models.CharField(max_length=10)),
                ('amountperperson', models.IntegerField()),
            ],
            options={
                'ordering': ['okota'],
            },
        ),
        migrations.CreateModel(
            name='SaccoMatatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pnumber', models.CharField(max_length=15)),
                ('Snumber', models.IntegerField()),
                ('Ntrips', models.IntegerField()),
            ],
            options={
                'ordering': ['Pnumber'],
            },
        ),
        migrations.AlterModelOptions(
            name='saccomanager',
            options={'ordering': ['Fname']},
        ),
        migrations.CreateModel(
            name='MatatuDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname1', models.CharField(max_length=10)),
                ('Lname1', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('Dlincence', models.IntegerField()),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.saccomanager')),
            ],
            options={
                'ordering': ['Fname1'],
            },
        ),
        migrations.CreateModel(
            name='MatatuConductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname12', models.CharField(max_length=10)),
                ('Lname12', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.matatudriver')),
            ],
            options={
                'ordering': ['Fname12'],
            },
        ),
    ]
